### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Keeperorowner** [lyaaz/FuckGram#17]
希望能增加防撤回功能

目前开源的可供参考的防撤回方案只有Re:telegram

https://github.com/Sakion-Team/Re-Telegram/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fnep%2Ftimeline%2Fre_telegram%2Ffeatures%2FNEWAntiRecall.java

**Comment by Chen-hai-0721** [comment]
消息过滤器的功能有bug

如果包含关键词的消息含有图片的话，
消息会被屏蔽，但是图片会仍然存在，这个建议优化一下

**Comment by Chen-hai-0721** [comment]
> > 目前有锁定底部按钮的功能，能否增加一个隐藏底部按钮的功能呢
> 
> 很好的想法，我一开始也是这么想的（这sb按钮放下面贼容易误触）。但是人太菜只能做成这样了，tg一个文件几万行源码都要看吐了，目前好不容易实现的禁用在某些情况下还会有bug，后面也懒得改了
> 
> > 希望之后能把设置界面内置到 Telegram客户端内部，就和tmoe那样，针对不同客户端都可以单独设置
> > 
> > [cinit/TMoe](https://github.com/cinit/TMoe)
> 
> 看着不错但是懒得实现 ~又不是不能用~
> 
> 里面的功能基本都是各处挖来的，部分可能有一点点改进，但是几乎完全没考虑兼容性，建议还是用其他维护比较积极的模块。

嗯，这个功能好像ayugram目前开源的代码已经实现了(虽然已经是一年之前的了)不过在9.66版本确实已经实现了完美的隐藏

不过第三方客户端的实现和通过hook实现应该还是有差别的

**Comment by Chen-hai-0721** [comment]
> 希望能增加防撤回功能
> 
> 目前开源的可供参考的防撤回方案只有Re:telegram
> 
> https://github.com/Sakion-Team/Re-Telegram/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fnep%2Ftimeline%2Fre_telegram%2Ffeatures%2FNEWAntiRecall.java

同求防撤回功能😋

**Comment by Chen-hai-0721** [comment]
> > 消息过滤器的功能有bug
> > 
> > 如果包含关键词的消息含有图片的话， 消息会被屏蔽，但是图片会仍然存在，这个建议优化一下
> 
> 这个也难改，目前就是半成品，涉及增删消息的都不好做，hook局限性还是挺大的。半年前看到 nullgram （第三方客户端）有相关的提交，不清楚完善没有。
> 
> 
> > > 希望能增加防撤回功能
> > > 目前开源的可供参考的防撤回方案只有Re:telegram
> > > [Sakion-Team/Re-Telegram@`main`/app%2Fsrc%2Fmain%2Fjava%2Fnep%2Ftimeline%2Fre_telegram%2Ffeatures%2FNEWAntiRecall.java](https://github.com/Sakion-Team/Re-Telegram/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fnep%2Ftimeline%2Fre_telegram%2Ffeatures%2FNEWAntiRecall.java?rgh-link-date=2024-11-09T07%3A43%3A29Z)
> > 
> > 同求防撤回功能😋
> 
> 理论上多个模块只要不同时启用相同的功能就一般不会冲突，可以一起用，我自己就看看频道，没这个需求，就算做了也很难腾出时间维护，建议还是直接用人家的

null的那个效果不怎么好，虽然文字没了，但是还会一直显示一个白条，ayugram是直接完全隐藏了
